name: StrafeDeaths
version: 2.0.0
main: strafeland.club.strafedeaths.Main
api-version: 1.13
authors: [zNotHydr0]
description: StrafeDeaths 2.0. Created by [zNotHydr0]
website: www.strafeland.club
commands:
  death:
    description: Main command for StrafeDeaths
    aliases: [deaths]
    permission: strafedeaths.admin
permissions:
  strafedeaths.admin:
    description: Admin permission for StrafeDeaths
    default: op